version: '3.1'
services:
  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: erashov
      POSTGRES_DB: asyncio_db
    ports:
      - "5431:5432"